package br.ifpb.dac.library_web.enumeration;

/**
 * DEVOLVIDO,REALIZADO,FINALIZA,ATRASADO,RENOVADO;
 *     RETURNED,ACCOMPLISHED,COMPLETED,DELAYED,RENEWED;
 */
public enum LoanStatus{
    DEVOLVIDO,REALIZADO,FINALIZADO,ATRASADO,RENOVADO;

}
